apiVersion: v1
kind: Pod
metadata:
  name: apiserver-prom-pod2
  labels:
    app: prom2
  namespace: prom
spec:
  containers:
  - name: apiserver-prom-container
    image: sayedppqq/prometheus-apiserver-task
    ports:
      - containerPort: 8090
