apiVersion: v1
kind: Pod
metadata:
  name: apiserver-prom-pod
  labels:
    app: prom
  namespace: prom
spec:
  containers:
  - name: apiserver-prom-container
    image: sayedppqq/prometheus-apiserver-task
    ports:
      - containerPort: 8090
